### ISSUE TITLE
message error when building nskinz

### ISSUE THREAD

**Issue by hoakaiser** [namazso/nSkinz#100]
1>------ Build started: Project: nSkinz, Configuration: Release Win32 ------
1>imgui.cpp
1>imgui_draw.cpp
1>config.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'deps\imgui\imgui_draw.cpp': No such file or directory
1>c1xx : fatal error C1083: Cannot open source file: 'deps\imgui\imgui.cpp': No such file or directory
1>FireGameEvent.cpp
1>PostDataUpdate.cpp
1>Sequence.cpp
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3927: '->': trailing return type is not allowed after a non-function declarator (compiling source file src\Hooks\Sequence.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3484: syntax error: expected '->' before the return type (compiling source file src\Hooks\Sequence.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3613: missing return type after '->' ('int' assumed) (compiling source file src\Hooks\Sequence.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3531: 'client_panorama': a symbol whose type contains 'auto' must have an initializer (compiling source file src\Hooks\Sequence.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C2146: syntax error: missing ';' before identifier 'dll' (compiling source file src\Hooks\Sequence.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3551: if a trailing return type is used then the leading return type shall be the single type-specifier 'auto' (not 'int') (compiling source file src\Hooks\Sequence.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file src\Hooks\Sequence.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3927: '->': trailing return type is not allowed after a non-function declarator (compiling source file src\Hooks\PostDataUpdate.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3484: syntax error: expected '->' before the return type (compiling source file src\Hooks\PostDataUpdate.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3613: missing return type after '->' ('int' assumed) (compiling source file src\Hooks\PostDataUpdate.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3531: 'client_panorama': a symbol whose type contains 'auto' must have an initializer (compiling source file src\Hooks\PostDataUpdate.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C2146: syntax error: missing ';' before identifier 'dll' (compiling source file src\Hooks\PostDataUpdate.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3551: if a trailing return type is used then the leading return type shall be the single type-specifier 'auto' (not 'int') (compiling source file src\Hooks\PostDataUpdate.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file src\Hooks\PostDataUpdate.cpp)
1>c:\users\viets\downloads\nskinz-master\src\hooks\postdataupdate.cpp(137): error C2672: 'platform::find_pattern': no matching overloaded function found
1>c:\users\viets\downloads\nskinz-master\src\hooks\postdataupdate.cpp(139): error C3536: 'set_abs_origin_addr': cannot be used before it is initialized
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3927: '->': trailing return type is not allowed after a non-function declarator (compiling source file src\Hooks\FireGameEvent.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3484: syntax error: expected '->' before the return type (compiling source file src\Hooks\FireGameEvent.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3613: missing return type after '->' ('int' assumed) (compiling source file src\Hooks\FireGameEvent.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3531: 'client_panorama': a symbol whose type contains 'auto' must have an initializer (compiling source file src\Hooks\FireGameEvent.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C2146: syntax error: missing ';' before identifier 'dll' (compiling source file src\Hooks\FireGameEvent.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3551: if a trailing return type is used then the leading return type shall be the single type-specifier 'auto' (not 'int') (compiling source file src\Hooks\FireGameEvent.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file src\Hooks\FireGameEvent.cpp)
1>c:\users\viets\downloads\nskinz-master\src\config.cpp(29): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory
1>imgui_impl_dx9.cpp
1>nSkinz.cpp
1>kit_parser.cpp
1>dllmain.cpp
1>c:\users\viets\downloads\nskinz-master\src\imgui_impl_dx9\imgui_impl_dx9.cpp(9): fatal error C1083: Cannot open include file: 'imgui.h': No such file or directory
1>sticker_changer.cpp
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3927: '->': trailing return type is not allowed after a non-function declarator (compiling source file src\nSkinz.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3484: syntax error: expected '->' before the return type (compiling source file src\nSkinz.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3613: missing return type after '->' ('int' assumed) (compiling source file src\nSkinz.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3531: 'client_panorama': a symbol whose type contains 'auto' must have an initializer (compiling source file src\nSkinz.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C2146: syntax error: missing ';' before identifier 'dll' (compiling source file src\nSkinz.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3551: if a trailing return type is used then the leading return type shall be the single type-specifier 'auto' (not 'int') (compiling source file src\nSkinz.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file src\nSkinz.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3927: '->': trailing return type is not allowed after a non-function declarator (compiling source file src\kit_parser.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3484: syntax error: expected '->' before the return type (compiling source file src\kit_parser.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3613: missing return type after '->' ('int' assumed) (compiling source file src\kit_parser.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3531: 'client_panorama': a symbol whose type contains 'auto' must have an initializer (compiling source file src\kit_parser.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C2146: syntax error: missing ';' before identifier 'dll' (compiling source file src\kit_parser.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C3551: if a trailing return type is used then the leading return type shall be the single type-specifier 'auto' (not 'int') (compiling source file src\kit_parser.cpp)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file src\kit_parser.cpp)
1>c:\users\viets\downloads\nskinz-master\src\kit_parser.cpp(126): error C2672: 'platform::find_pattern': no matching overloaded function found
1>c:\users\viets\downloads\nskinz-master\src\kit_parser.cpp(126): error C2789: 'sig_address': an object of const-qualified type must be initialized
1>c:\users\viets\downloads\nskinz-master\src\kit_parser.cpp(126): note: see declaration of 'sig_address'
1>c:\users\viets\downloads\nskinz-master\src\kit_parser.cpp(129): error C3536: 'sig_address': cannot be used before it is initialized
1>c:\users\viets\downloads\nskinz-master\src\kit_parser.cpp(183): error C2672: 'platform::find_pattern': no matching overloaded function found
1>c:\users\viets\downloads\nskinz-master\src\kit_parser.cpp(183): error C2789: 'sticker_sig': an object of const-qualified type must be initialized
1>c:\users\viets\downloads\nskinz-master\src\kit_parser.cpp(183): note: see declaration of 'sticker_sig'
1>c:\users\viets\downloads\nskinz-master\src\kit_parser.cpp(186): error C3536: 'sticker_sig': cannot be used before it is initialized
1>update_check.cpp
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(80): error C3927: '->': trailing return type is not allowed after a non-function declarator
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(80): error C3484: syntax error: expected '->' before the return type
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(80): error C3613: missing return type after '->' ('int' assumed)
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(80): error C2371: 'client_panorama': redefinition; different basic types
1>c:\users\viets\downloads\nskinz-master\src\nskinz.hpp(39): note: see declaration of 'client_panorama'
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(80): error C3531: 'client_panorama': a symbol whose type contains 'auto' must have an initializer
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(80): error C2146: syntax error: missing ';' before identifier 'dll'
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(81): error C3551: if a trailing return type is used then the leading return type shall be the single type-specifier 'auto' (not 'int')
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(81): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(85): error C2440: 'return': cannot convert from 'const char *' to 'int'
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(85): note: There is no context in which this conversion is possible
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(86): error C2617: 'dll': inconsistent return statement
1>c:\users\viets\downloads\nskinz-master\src\nskinz.cpp(80): note: see declaration of 'dll'
1>platform.cpp
1>render.cpp
1>netvar_manager.cpp
1>c:\users\viets\downloads\nskinz-master\src\update_check.cpp(30): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory
1>gui.cpp
1>c:\users\viets\downloads\nskinz-master\src\gui.cpp(31): fatal error C1083: Cannot open include file: 'imgui.h': No such file or directory
1>item_definitions.cpp
1>c:\users\viets\downloads\nskinz-master\src\render.cpp(34): fatal error C1083: Cannot open include file: 'imgui.h': No such file or directory
1>Done building project "nSkinz.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

help me pls

**Comment by M1XT3NZ** [comment]
he probably doesn't even know how that works. 
you downloaded it over the Github download button that means you need to download 
https://github.com/ocornut/imgui/tree/a6ff14d66e66c167fbcbc01c4aea1a8361e3dc4e
and
https://github.com/nlohmann/json/tree/183390c10b8ba4aa33934ae593f82f352befefc8
also and put those in the deps folder.

**Comment by anarh1st47** [comment]
![meme](https://i.imgur.com/2kWaS1m.png)

**Comment by ChillVibez** [comment]
1>gui.obj : error LNK2001: unresolved external symbol "bool __cdecl ImGui::InputText(char const *,char *,unsigned int,int,int (__cdecl*)(struct ImGuiInputTextCallbackData *),void *)" (?InputText@ImGui@@YA_NPBDPADIHP6AHPAUImGuiInputTextCallbackData@@@ZPAX@Z)
1>C:\Users\soda\Desktop\nSkinz-master\Release\nSkinz.dll : fatal error LNK1120: 1 unresolved externals

after putting in deps
