### ISSUE TITLE
W s movement keys don't work properly

### ISSUE THREAD

**Issue by KiszonyKacper** [namazso/nSkinz#103]
Hello there, my w and s keys don't work while i'm using nskinz in cs go. Any ideas what should fix the problem?

**Comment by M1XT3NZ** [comment]
i "fixed" it (basically just uncommented 2 things and it did work again. I don't know what really causes this to happen. I give it 2 days of testing and then I'm going to do a pull req.

**Comment by M1XT3NZ** [comment]
So This will soon be fixed on the main branch. Just wait a bit ;)

**Comment by M1XT3NZ** [comment]
This is now fixed pls close
