### ISSUE TITLE
Still Undetected?

### ISSUE THREAD

**Issue by sigmataf** [namazso/nSkinz#104]
*title* anyone using it? anyone got banned?

**Comment by M1XT3NZ** [comment]
#98 #96

**Comment by wardinh0** [comment]
Yea it's safe, but of course people will be banned, it's a paste, you need to do your shit to make the signature UD. I'd recommend something using VeraCrypt, that shit's good

**Comment by sigmataf** [comment]
> Yea it's safe, but of course people will be banned, it's a paste, you need to do your shit to make the signature UD. I'd recommend something using VeraCrypt, that shit's good

Thank you
