### ISSUE TITLE
Why my weapons skin is black

### ISSUE THREAD

**Issue by gonjay** [namazso/nSkinz#109]
![image](https://user-images.githubusercontent.com/2020255/45793554-49f25e80-bcc5-11e8-867d-c012944b9994.png)

**Comment by M1XT3NZ** [comment]
can you throw the weapon on the ground and pick it up again? also tab in and out
1 time

**Comment by gonjay** [comment]
@M1XT3NZ I tried it and found no effect.

**Comment by M1XT3NZ** [comment]
type record x;stop in console and put the wear of the weapon a bit up.

**Comment by M1XT3NZ** [comment]
oh no i see what you did you put the wear up and scale and everything

**Comment by gonjay** [comment]
Thanks, it's working!But why is this?

**Comment by Primeknight19** [comment]
@gonjay or @M1XT3NZ can you tell me which injector are you using. Sorry asking this question again.

**Comment by M1XT3NZ** [comment]
> 
> 
> @gonjay or @M1XT3NZ can you tell me which injector are you using. Sorry asking this question again.

Dude this GitHub is not for asking those questions. You have access to the internet. http://lmgtfy.com/?q=best+undetected+injector

**Comment by Jeimy041** [comment]
> @gonjay or @M1XT3NZ can you tell me which injector are you using. Sorry asking this question again.

As you may not found what you like on google, I´m gonna tell you that I personally use RandoInjector no bans yet and I´ve been using it for months oh and btw remember changing and adding the junks of the source in order not to get banned.

**Comment by M1XT3NZ** [comment]
we are not talking about injectors here.
