### ISSUE TITLE
chinese display issues

### ISSUE THREAD

**Issue by madlifer** [namazso/nSkinz#11]
Hello,sir.  we are chinese users.but this cheat dont support chinese display.

look this：
https://gyazo.com/0805beea654d8d7d2120ee3eb0a188ef
https://gyazo.com/8876e0f9bc5b20c7db31b1f646a34ebe

We have an open group of about a few hundred people. Many people want to have a perfect skinchanger.

So we would like to ask you to create a version of Chinese support for us. As a reward for taking your time, we can offer you $ 50 (most people do not like paying for help, and we are all together for this, so we can only get up to this level for you)
If you agree, then I can PM me or reply to get my contact, and then we can discuss the Chinese display problem.

**Comment by wi1h** [comment]
Refer to #6. With money involved, I'm not sure, but yeah.

**Comment by Garry050** [comment]
i making chinese version nSkinz. (only support chinese. i will make Japanese and Russian and International version)
<img src="https://i.ppn.pw/cc/645ca6c4/rfcab0f2d.png">
<img src="https://i.ppn.pw/cc/645ca6c4/e1143fb3f.png">
i think i can complete make chinese version nskinz some hours later. But I don't know if this (i mean unofficially / my built) binary can be release.

@namazso Can i release my build binary?

**Comment by Garry050** [comment]
sucessful translate. it's chinese user version.
<img src=https://i.ppn.pw/cc/645ca6c4/h65fb5701.png>

**Comment by Skyline23** [comment]
"StatTrak" can translate into "击杀数" imo that will be better

**Comment by Garry050** [comment]
thx. i think 90% translate to chinese nSkinz (why 90% = i'm not chinese -_-)
<img src="https://i.ppn.pw/cc/645ca6c4/f414d7b1f.png">
<img src="https://i.ppn.pw/cc/645ca6c4/n90bb6bf0.png">
<img src="https://i.ppn.pw/cc/645ca6c4/pb7c896ad.png">
<img src="https://i.ppn.pw/cc/645ca6c4/xbf956ea3.png">

is that okay?

**Comment by Skyline23** [comment]
Yes. If I remember correctly "PaintSeed" is kinda of stuff that can change the appearance of skin. Maybe it can translate into "皮肤外观种子"

**Comment by Garry050** [comment]
okay...
<img src="https://i.ppn.pw/cc/645ca6c4/q72f0b5ce.png">

**Comment by Skyline23** [comment]
(๑•̀ㅂ•́)و✧ Thats petty dope

**Comment by namazso** [comment]
@Garry050 You can release binary of course. I suggest that you read the license: https://github.com/namazso/nSkinz/blob/master/LICENSE
If you release the source on github (as a fork preferably so you can merge updates from here) I might link to it in the README. I was considering adding a full internationalization engine before, but decided its not worth it.

**Comment by Garry050** [comment]
https://github.com/Garry050/nSkinz/tree/zh-CN
done

**Comment by Skyline23** [comment]
I took a look into the source then i found some errors.

[①](https://github.com/Garry050/nSkinz/blob/zh-CN/nSkinz/src/ItemDefinitions.cpp#L105) "击杀数" → "暗金" or "奇异"
[②](https://github.com/Garry050/nSkinz/blob/zh-CN/nSkinz/src/ItemDefinitions.cpp#L103) "原型" → "自制"
[③](https://github.com/Garry050/nSkinz/blob/zh-CN/nSkinz/src/Interface.cpp#L149)"不可用匕首,可穿 -_-" → "针对匕首和手套"
[④](https://github.com/Garry050/nSkinz/blob/zh-CN/nSkinz/src/Interface.cpp#L193)"外观" → "磨损值"
[⑤](https://github.com/Garry050/nSkinz/blob/zh-CN/nSkinz/src/Interface.cpp#L110)"涂装套件" → "手套名称"//I don't know if it will be shown or not in the menu

**Comment by Garry050** [comment]
1,2 won't replace it. because i want to priority Valve's translation (ツ)
anyway, thx 3,4,5 merged and released binary

**Comment by namazso** [comment]
In case someone makes a localized port in the future please open a new issue, i'm closing this one.
