### ISSUE TITLE
How to bypass VAC VMT Detection ?

### ISSUE THREAD

**Issue by theShadoW651** [namazso/nSkinz#116]
Is it possible to change the way that vmt work or change vmt with some other method? I am getting into c++ . Dont hate. Sorry for my bad English.

**Comment by anarh1st47** [comment]
nSkinz doesnt hook blacklisted objects

**Comment by theShadoW651** [comment]
thx for the respond

На 03.10.2018 19:02 "Dmitry" <notifications@github.com> написа:

**Comment by namazso** [comment]
reverse what do they detect, and dont do those things duh.
