### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by theShadoW651** [namazso/nSkinz#117]
![untitled](https://user-images.githubusercontent.com/39189627/46477291-35bb6080-c79f-11e8-9611-3808c1084eb2.png)

Update : 
Somthing fixed

![ddd](https://user-images.githubusercontent.com/39189627/46478259-67cdc200-c7a1-11e8-8829-dd474f007b26.png)

**Comment by M1XT3NZ** [comment]
#100
