### ISSUE TITLE
I'm new, need some help

### ISSUE THREAD

**Issue by Lito7** [namazso/nSkinz#118]
Could someone send me a working dll to inject, i have been trying to use the Skinchanger, and since the update it crashes, but i know this code is working however i dont know anything about dll and how to compile and also i'm quite busy, i just want to play some csgo with some nice skins

**Comment by flexthekid** [comment]
Unfortunately sending a working dll can't do. If pepole would've just use it, it would get insta detected,

**Comment by Lito7** [comment]
I managed to get everything working, its ok now

**Comment by Lito7** [comment]
I managed to get it working!
