### ISSUE TITLE
invalid numeric argument '/Wno-unused-private-field'	nSkinz

### ISSUE THREAD

**Issue by Tyylr** [namazso/nSkinz#12]
When compiling i get the error "Error	D8021	invalid numeric argument '/Wno-unused-private-field'	nSkinz	C:\Users\USER\Desktop\nSkinz-master\nSkinz\cl"

**Comment by Tyylr** [comment]
its a prob in update check becasue i removed that and it compiled fine

**Comment by Tyylr** [comment]
ran in debug had to remove some stuff in update check now its working fine please close

**Comment by namazso** [comment]
Because it is a clang only compiler argument. Just remove it if you compile with msvc
