### ISSUE TITLE
Cannot open source file "source file"

### ISSUE THREAD

**Issue by broesel233** [namazso/nSkinz#122]
I am trying to compile nSkinz for myself but it gives me the Error E1969: Cannot open source file "the source file spezified". This happens on every cpp file with #include in it, can someone help me?

**Comment by M1XT3NZ** [comment]
you didn't clone it. (so you didn't use GitHub desktop or else)

**Comment by broesel233** [comment]
I cloned it with "git clone https://github.com/namazso/nSkinz.git" in the git bash

**Comment by M1XT3NZ** [comment]
can you screenshot the error, please? (the complete error section if you can.)

**Comment by broesel233** [comment]
@anarh1st47 Thanks it worked now
