### ISSUE TITLE
Missing files : imgui.h/.cpp imgui_draw.cpp EDIT : Fixed

### ISSUE THREAD

**Issue by theShadoW651** [namazso/nSkinz#132]
EDIT : Fixed
I have issue with the source. 
![capture](https://user-images.githubusercontent.com/39189627/50338947-a9f3dd80-051e-11e9-80fa-dd2564c34b20.PNG)

These files are missing. Any ideas??

**Comment by tankbutch** [comment]
and how do we fix this my good sir?

**Comment by anarh1st47** [comment]
clone it recursively

**Comment by blejeff** [comment]
what do you mean recursively? help

**Comment by M1XT3NZ** [comment]
Download GitHub Desktop the other stuff should be obvious if you have a
brain..
