### ISSUE TITLE
Nobody want to update this? 

### ISSUE THREAD

**Issue by demonicPbunny** [namazso/nSkinz#133]
??

**Comment by M1XT3NZ** [comment]
is there a need to update it?

**Comment by demonicPbunny** [comment]
ForceFullUpdate is broken and record x ; stop does not work anymore

**Comment by M1XT3NZ** [comment]
> 
> 
> ForceFullUpdate is broken and record x ; stop does not work anymore

if you click update in the cheat it works.. i just tried it myself.
Probably a you problem i guess?

**Comment by Jeimy041** [comment]
It doesnt wotk for me the first time I inject it on a new account, but after playing some time reinjecting it seems to work well IDK if this helps.

**Comment by namazso** [comment]
feel free to send PRs, i test and merge them, and still function as the project maintainer in general.
