### ISSUE TITLE
Vac Banned 

### ISSUE THREAD

**Issue by bakill3** [namazso/nSkinz#135]
Used for 3-4 hours randoInjector, added junk to all cpp & used winlicense aswell

**Comment by Jeimy041** [comment]
I use this without junkcode and wityh rando injector. I´ve never been banned.
Tip: VMProtect the injector and the dll.

**Comment by Shaxzy** [comment]
I don’t use junkcodes or VMProtect and I have never been VAC banned with this. Just rename features snd shit

**Comment by Clementslay** [comment]
> I don’t use junkcodes or VMProtect and I have never been VAC banned with this. Just rename features and shit

can u help me out bro?

**Comment by namazso** [comment]
winlicense and themida is known to get you banned, regardless of cheat.
also, unless it is some sort of generic detection, it is not scope of the project.
