### ISSUE TITLE
Tutorial on how to use this

### ISSUE THREAD

**Issue by Clementslay** [namazso/nSkinz#136]

**Comment by Shaxzy** [comment]
Download source, compile it, inject it into csgo using a .dll injector.

**Comment by Clementslay** [comment]
would be really cool if u told me what software i need for this

**Comment by M1XT3NZ** [comment]
visual studio.......

**Comment by Clementslay** [comment]
@M1XT3NZ hey  can u help me with the injection process.... and what software i may need for it?

**Comment by Shaxzy** [comment]
I helped him through discord. 👍🏻

**Comment by Jeimy041** [comment]
Nice

**Comment by namazso** [comment]
build with your favorite compiler and inject
