### ISSUE TITLE
Random disconnect while playing

### ISSUE THREAD

**Issue by theShadoW651** [namazso/nSkinz#137]
![image](https://user-images.githubusercontent.com/39189627/54071623-c67af880-4277-11e9-9984-c0fd028f20ba.png)
I am getting this error while playing mm. Any idea why?

**Comment by anarh1st47** [comment]
try another injector

**Comment by Jeimy041** [comment]
Try another injector ot VMProtect the one you have + the dll

**Comment by Alexey25322** [comment]
If you still need help, msg me on Discord: Alexey2532#9439

**Comment by namazso** [comment]
duplicate of #27
