### ISSUE TITLE
Question about imgui

### ISSUE THREAD

**Issue by AlphaBeast** [namazso/nSkinz#141]
Hey guys, anyone know how to change color of the buttons, slider etc in game? It's not working for me if I go to imgui.cpp and then go to line 741 and change code of the colors and then compile it doesn't work. Nothing have changed. I want to change colors of this gray buttons etc. I'm bored of this color. So can anyone help me? 

Maybe @namazso ?

**Comment by anarh1st47** [comment]
you can use imgui::pushstylevar(with popstylevar after) for specific object or set global imgui style (writing to imgui::getstyle)

**Comment by AlphaBeast** [comment]
@anarh1st47 I don't understand bruh :/ I don't understand how to edit imgui style so I suck in it. Can you please specify your reply for "braindeads" what to do exactly? I just want to change color of that buttons, sliders etc to a specific color.

**Comment by namazso** [comment]
https://github.com/namazso/nSkinz/blob/master/src/render.cpp#L228
