### ISSUE TITLE
vac error?

### ISSUE THREAD

**Issue by KenZo2k2** [namazso/nSkinz#143]
plz fix fasttttt

**Comment by Aethstetic** [comment]
not sure if you realized this project has been dead for a good while now

**Comment by M1XT3NZ** [comment]
It's not "dead"

There is just no need to update it?
The VAC error is probably a "you" problem. 

could be fixed with (vmprotect, etc)

**Comment by Jeimy041** [comment]
Simple solution, take your dll, take your injector (I recommend rando injector), get VMProtect, go ahead and VMProtect both dll and the injector and fixed no more VAC errors

**Comment by namazso** [comment]
duplicate of #27 / out of scope
