### ISSUE TITLE
SetWeaponModel changed 

### ISSUE THREAD

**Issue by JimmyBassy** [namazso/nSkinz#149]
SetWeaponModel's index changed to 245

**Comment by Alpha878** [comment]
> SetWeaponModel's index changed to 245

@JimmyBassy Where can I find SetWeaponModel Index?

Is it this?
item->GetClientNetworkable()->PreDataUpdate(0); (and just change 0 to 245?)

I'm getting pure server file pak game (...).pak after a few seconds of playing. Almost instantly after joining the game. I didn't had this issue before the update. Can you help?

**Comment by JimmyBassy** [comment]
No, I found out it is not needed in this cheat or at least I dont find it, to solve that verify the game files and protect your cheat and injector with VMP
