### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by r58iiz** [namazso/nSkinz#156]
I am getting 234 errors while trying to compile it in VS 2019. I have retargeted the solution. ~~do I need to use the 2017 one?~~ Cant get 2017 one.
[Link](https://hastebin.com/ulovubusic.bash)

**Comment by campingtent** [comment]
To fix it all you need to do is download 2017 build tool and compiler your project

**Comment by r58iiz** [comment]
The thing I just said was I cant get VS 2017.

**Comment by M1XT3NZ** [comment]
And why? It’s free

**Comment by namazso** [comment]
fixed in 51c26ab8ae12b96f7ae33849a10cd80055ddceca
