### ISSUE TITLE
200+ Errors, even with different built tools?

### ISSUE THREAD

**Issue by Clxrk** [namazso/nSkinz#158]
Using Visual Studio 2019.

Build Tools installed:
- C++ Win XP for Tools in VS 2017
- C++ 2019 Redristibutable Update
- C++ CLI Support for v141 Buildtools (14.16)
- C++ CMake Tools for Windows
- MSVC v140 - VS 2015 C++ Buildtools (v14.00)
- MSVC v141 - VS 2017 C++ x64/x86-Buildtools (v14.16)
- MSVC v142 - VS 2019 C++ x64/x86-Buildtools (v14.22)
- Windows Universal CRT SDK
- C++ Corefeatures
- Windows 10 SDK (10.0.18362.0)
- Windows Universal C-Runtime

Any tips?

**Comment by JimmyBassy** [comment]
Show the errors that you get please

**Comment by namazso** [comment]
fixed in 51c26ab8ae12b96f7ae33849a10cd80055ddceca
