### ISSUE TITLE
vac error

### ISSUE THREAD

**Issue by ph4nt0m23** [namazso/nSkinz#159]
Hey guys pls help I cant play for like 2 rounds and it says cannot play on vac secured servers pls help me

**Comment by anarh1st47** [comment]
use undetected injector

**Comment by ph4nt0m23** [comment]
what undetected injector can u recommend one

**Comment by ph4nt0m23** [comment]
and how to do it do u have a tutorial

**Comment by namazso** [comment]
duplicate of #27
