### ISSUE TITLE
c4 skin

### ISSUE THREAD

**Issue by HECCYE** [namazso/nSkinz#165]
Hi, i was just wondering if applying skin to c4 is possible.

**Comment by namazso** [comment]
iirc no, but you're free to try it
you just have to add C4 to this vector: https://github.com/namazso/nSkinz/blob/master/src/item_definitions.cpp#L97

**Comment by HECCYE** [comment]
It just crashes a soon as i click on c4. but thank you anyways

**Comment by namazso** [comment]
i guess this answers your question then
