### ISSUE TITLE
Skins not working properly (quite ugly)

### ISSUE THREAD

**Issue by xanaxw** [namazso/nSkinz#168]
I play on 4:3 stretched 1024x768.

All my video settings are on low except for my shaders which are on very high.

If it's a problem caused by me, I apologize for wasting your time, but it is my first time using this skin-changer.

![20190930155725_1](https://user-images.githubusercontent.com/28925642/65881595-4eebf280-e39c-11e9-98ad-6e47ef6e4448.jpg)

**Comment by M1XT3NZ** [comment]
This happens because you don’t use the correct skin for the knife. There
are multiple of the same skin try each one till you get the right one.
(Hope i don’t mix up 2 different Problems)

**Comment by xanaxw** [comment]
I tried all the doppler & gamma doppler skins on the m9 bayonet and none of them worked and looked like this.

**Comment by xanaxw** [comment]
Apparently, it was because of my resolution. 
Problem solved, sorry for wasting & making this thread guys. 

Have a great day.

![Screenshot_1](https://user-images.githubusercontent.com/28925642/65882308-78594e00-e39d-11e9-9b5b-27791b3b1a6f.png)
