### ISSUE TITLE
Visual Studio build error

### ISSUE THREAD

**Issue by DeathlyCoder** [namazso/nSkinz#186]
I'm using Microsoft Visual Studio Community 2019 Version 16.4.0

`1>c1xx : fatal error C1083: Cannot open source file: 'deps\imgui\imgui.cpp': No such file or directory
1>imgui_impl_dx9.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'deps\imgui\imgui_draw.cpp': No such file or directory
1>nSkinz.cpp
1>kit_parser.cpp
1>dllmain.cpp
1>D:\Tools\Git\nSkinz\src\Imgui_impl_dx9\imgui_impl_dx9.cpp(9,10): fatal error C1083: Cannot open include file: 'imgui.h': No such file or directory
1>sticker_changer.cpp
1>update_check.cpp
1>D:\Tools\Git\nSkinz\src\config.cpp(29,10): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory
1>platform.cpp
1>render.cpp
1>netvar_manager.cpp
1>gui.cpp
1>item_definitions.cpp
1>D:\Tools\Git\nSkinz\src\update_check.cpp(30,10): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory
1>D:\Tools\Git\nSkinz\src\gui.cpp(31,10): fatal error C1083: Cannot open include file: 'imgui.h': No such file or directory
1>D:\Tools\Git\nSkinz\src\render.cpp(34,10): fatal error C1083: Cannot open include file: 'imgui.h': No such file or directory
1>Done building project "nSkinz.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by namazso** [comment]
maybe try following the steps in the readme
