### ISSUE TITLE
Errors in compiling

### ISSUE THREAD

**Issue by travispresk0** [namazso/nSkinz#190]
I'm kind of new to programming so please pardon me. 
I get these errors when I compile with Visual Studio 2019:

1>------ Build started: Project: nSkinz, Configuration: Release Win32 ------
1>imgui.cpp
1>imgui_draw.cpp
1>config.cpp
1>c1xx: fatal error C1083: Cannot open source file: 'deps\imgui\imgui.cpp': No such file or directory
1>c1xx: fatal error C1083: Cannot open source file: 'deps\imgui\imgui_draw.cpp': No such file or directory
1>imgui_impl_dx9.cpp
1>update_check.cpp
1>render.cpp
1>gui.cpp
1>C:\Users\aldri\Desktop\nSkinz-master\src\Imgui_impl_dx9\imgui_impl_dx9.cpp(9,10): error C1083:  Cannot open include file: 'imgui.h': No such file or directory
1>C:\Users\aldri\Desktop\nSkinz-master\src\update_check.cpp(30,10): error C1083:  Cannot open include file: 'nlohmann/json.hpp': No such file or directory
1>C:\Users\aldri\Desktop\nSkinz-master\src\config.cpp(29,10): error C1083:  Cannot open include file: 'nlohmann/json.hpp': No such file or directory
1>C:\Users\aldri\Desktop\nSkinz-master\src\gui.cpp(31,10): error C1083:  Cannot open include file: 'imgui.h': No such file or directory
1>C:\Users\aldri\Desktop\nSkinz-master\src\render.cpp(34,10): error C1083:  Cannot open include file: 'imgui.h': No such file or directory
1>Done building project "nSkinz.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Pitool** [comment]
i got it about 2 years ago when i tried to compile it first time, when choosing the compilator try to change it for another i do this then and it worked because i got two compilators to choose and the second one was fine, i hope i helped :)

**Comment by namazso** [comment]
try following the readme
