### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by asdasd123www** [namazso/nSkinz#194]
How to deal with the phenomenon of disorderly code when opening

**Comment by isse101** [comment]
What is "disorderly code" and what are you opening it in?

**Comment by asdasd123www** [comment]
Thank you reply, I have deal it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"isse"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月17日(星期一) 下午3:32
收件人:&nbsp;"namazso/nSkinz"<nSkinz@noreply.github.com&gt;;
抄送:&nbsp;"15"<1027338737@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [namazso/nSkinz] Please help me! (#194)




What is "disorderly code" and what are you opening it in?
