### ISSUE TITLE
again about porting to linux

### ISSUE THREAD

**Issue by OtakuLinux** [namazso/nSkinz#196]
Hello! I am not a programmer and I cannot port this skinchanger to linux. But I would like someone to do this. If someone wants to explain to me how to do this or someone has already ported skinchanger to linux please share the link here.
P. S. Sorry for my english, this is not my native language

**Comment by sonicrules11** [comment]
https://github.com/aixxe/csgo-skinchanger-linux

update this and you're good to go

**Comment by OtakuLinux** [comment]
I would like to add stickers, but I do not know how to do it.
