### ISSUE TITLE
I get vac banned in 1 day (12/04/20)

### ISSUE THREAD

**Issue by Anibal-F** [namazso/nSkinz#199]

**Comment by wowlicha2** [comment]
i think that you need to use vmprotect and junk code.
Dont forget to change the junk code every week only to be sure..
i hope my commentary where useful for you

**Comment by iraizo** [comment]
> 
> 
> i think that you need to use vmprotect and junk code.
> Dont forget to change the junk code every week only to be sure..
> i hope my commentary where useful for you

bullshit

**Comment by thefirstDudu** [comment]
> > i think that you need to use vmprotect and junk code.
> > Dont forget to change the junk code every week only to be sure..
> > i hope my commentary where useful for you
> 
> bullshit

It´s ok about junk code and vmprotect but i thought you also need to add Veracrypt, and a good injector in safemode only to avoid the vacban. if you think that a free hack is going to never be vac banned, you don´t understanded nothing about hacks in csgo. Thank´s for reading

**Comment by iraizo** [comment]
> 
> 
> > > i think that you need to use vmprotect and junk code.
> > > Dont forget to change the junk code every week only to be sure..
> > > i hope my commentary where useful for you
> > 
> > 
> > bullshit
> 
> It´s ok about junk code and vmprotect but i thought you also need to add Veracrypt, and a good injector in safemode only to avoid the vacban. if you think that a free hack is going to never be vac banned, you don´t understanded nothing about hacks in csgo. Thank´s for reading

i dont think you understand how vac even works, you can use any injector even loadlibraryA works, junkcode will do nothing nor will vmprotect do something

**Comment by namazso** [comment]
duplicate of #27 / out of scope
