### ISSUE TITLE
D3D9.h is missing

### ISSUE THREAD

**Issue by ficaman47** [namazso/nSkinz#20]
Eveytime i try to build this i get a error that says d3d9 is missing.I linked the directx sdk but it still says its missing so i made d3d9 manually and its still missing

**Comment by namazso** [comment]
This is your failure and not the changer's. Learn how to install and use libraries..

**Comment by ficaman47** [comment]
i never said it was the changers fault my visual studio was the problem i wouldnt confimthe additional libary so i just reinstalled it and it works fine

**Comment by namazso** [comment]
Ok, and this is not a visual studio support forum, but the skinchanger's issue tracker
