### ISSUE TITLE
platform.hpp error

### ISSUE THREAD

**Issue by Tipsymario3** [namazso/nSkinz#207]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'search': is not a member of 'std' (compiling source file src\render.cpp)	nSkinz	
src\Utilities\platform.hpp	75	
Any help? I'm using Visual Studio 2019 with latest Windows 10 SDK.

**Comment by HighDelay** [comment]
#include <algorithm>

**Comment by HighDelay** [comment]
`#include <algorithm>`

**Comment by Oraples** [comment]
yes pls help

**Comment by MADmaster511** [comment]
> `#include <algorithm>`

You talking about this being written down somewhere or what?

**Comment by HighDelay** [comment]
> > `#include <algorithm>`
> 
> You talking about this being written down somewhere or what?

Write it below those `#include` in platform.hpp
You know how to do it right ?

**Comment by tuttizpro218** [comment]
`#include <algorithm> //add this to platform.hpp `

**Comment by namazso** [comment]
fixed in 893cc0114c624b5aeb6fdee2f445c7acc8807d1e
