### ISSUE TITLE
1>Renderer.obj : error LNK2001: unresolved external symbol "long __cdecl ImGui_ImplDX9_WndProcHandler(struct HWND__ *,unsigned int,unsigned int,long)" (?ImGui_ImplDX9_WndProcHandler@@YAJPAUHWND__@@IIJ@Z)

### ISSUE THREAD

**Issue by eue398** [namazso/nSkinz#21]
When I update the ImGui version to the latest one I get this error
1>Renderer.obj : error LNK2001: unresolved external symbol "long __cdecl ImGui_ImplDX9_WndProcHandler(struct HWND__ *,unsigned int,unsigned int,long)" (?ImGui_ImplDX9_WndProcHandler@@YAJPAUHWND__@@IIJ@Z)

**Comment by wi1h** [comment]
https://github.com/ocornut/imgui/blob/master/examples/directx9_example/imgui_impl_dx9.h#L19-L24

**Comment by eue398** [comment]
anyone???? p;ls

**Comment by terryadavis** [comment]
Jeez I fixed it in https://github.com/namazso/nSkinz/pull/22

**Comment by wi1h** [comment]
oh lmao didn't know that changed. my bad

**Comment by eue398** [comment]
@wi1h hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh fkn nigger

**Comment by namazso** [comment]
PR merged, thanks.

**Comment by astron-dev** [comment]
I get the same Linker error with the updated function

**Comment by namazso** [comment]
I pushed an update an hour ago that supposedly fixed this. Have you tried the following commands:
```
git pull
git submodule update --recursive```
Does the problem still persist after these?

**Comment by astron-dev** [comment]
thx fixed it <3
