### ISSUE TITLE
nSkinz build failed

### ISSUE THREAD

**Issue by D-e-r-e-k-M** [namazso/nSkinz#210]
`1>------ Build started: Project: nSkinz, Configuration: Release Win32 ------
1>render.cpp
1>C:\Users\user\Documents\GitHub\nSkinz\src\Utilities\platform.hpp(74,25): error C2039: 'search': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\map(25): message : see declaration of 'std'
1>C:\Users\user\Documents\GitHub\nSkinz\src\render.cpp(358): message : see reference to function template instantiation 'uintptr_t platform::find_pattern<12>(const char *,const char (&)[12],const char (&)[12])' being compiled
1>C:\Users\user\Documents\GitHub\nSkinz\src\Utilities\platform.hpp(74,1): error C3861: 'search': identifier not found
1>Done building project "nSkinz.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

I do not know exactly what is happening here, I am compiling it using visual studio 2019 and I cloned it properly (i think) from github

**Comment by jackKiZhu** [comment]
use v141

**Comment by HighDelay** [comment]
#207

**Comment by tuttizpro218** [comment]
`#include <algorithm> //add this to platform.hpp `

**Comment by namazso** [comment]
fixed in 893cc0114c624b5aeb6fdee2f445c7acc8807d1e
