### ISSUE TITLE
'search' is not a member of std

### ISSUE THREAD

**Issue by drain3r** [namazso/nSkinz#213]
On line 74 of https://github.com/namazso/nSkinz/blob/master/src/Utilities/Platform.hpp
it says std::search
I'm using vs2019 to try and compile and it says
Error	C2039	'search': is not a member of 'std' (compiling source file src\render.cpp)
-=-=-=-=-=-=
Error	C3861	'search': identifier not found (compiling source file src\render.cpp)
These both stem from the same line #74 in platform.hpp . Am I missing something? How do I get it to compile even though it says search is not a member of std?

**Comment by Tipsymario3** [comment]
Just add "#include <algorithm>" to the start of that file under where it says all the other includes (without the quotations)

**Comment by Boboguybro** [comment]
> Just add "#include " to the start of that file under where it says all the other includes (without the quotations)

Can i ask which line are u talking about?

**Comment by tuttizpro218** [comment]
> > Just add "#include " to the start of that file under where it says all the other includes (without the quotations)
> 
> Can i ask which line are u talking about?

#include <algorithm> add this to playform.hpp

**Comment by namazso** [comment]
fixed in 893cc0114c624b5aeb6fdee2f445c7acc8807d1e
