### ISSUE TITLE
How to add new skins

### ISSUE THREAD

**Issue by FlameProfi** [namazso/nSkinz#224]
How?

**Comment by namazso** [comment]
not possible, you can only use the skins the game provides

**Comment by FlameProfi** [comment]
Are skins from the game itself updated automatically?

**Comment by FlameProfi** [comment]
I use you skinchanger in osiris, but default cs:go skins don't updated

**Comment by namazso** [comment]
> Are skins from the game itself updated automatically?

yes they should, skin and sticker list is automatically pulled from the game. only things like weapons (eg. a new knife) aren't updated automatically. If you want any kind of support confirm that your issue happens in upstream (aka this project)
