### ISSUE TITLE
37 issues and cant open source file "json.hpp"

### ISSUE THREAD

**Issue by noxipoop** [namazso/nSkinz#23]
http://prntscr.com/h2ixy0
It gives me 37 errors and it keeps saying it cant open json.hpp i put the json.hpp in the json folder since it wasnt in there originally and it continues to not work...
http://prntscr.com/h2iykl
http://prntscr.com/h2iyo3
http://prntscr.com/h2iyqg
please help

EDIT: imgui is fixed but json still doesnt open

  imgui_impl_dx9.cpp
  imgui.cpp
  imgui_draw.cpp
  Configuration.cpp
  UpdateCheck.cpp
src\Configuration.cpp(5): fatal error C1083: Cannot open include file: 'json.hpp': No such file or directory
  Renderer.cpp
  Interface.cpp
src\UpdateCheck.cpp(5): fatal error C1083: Cannot open include file: 'json.hpp': No such file or directory

**Comment by wi1h** [comment]
did you download the submodules? seems like you didn't

**Comment by namazso** [comment]
if you cannot even follow the first step of the guide then you have serious problems, get help.
That really doesnt look like a `git clone --recursive`
