### ISSUE TITLE
Cannot compile anymore

### ISSUE THREAD

**Issue by CalvinBens** [namazso/nSkinz#236]
Getting errors like :

Cannot open source file: 'deps\imgui\imgui.cpp': No such file or directory	nSkinz	
Cannot open source file: 'deps\imgui\imgui_draw.cpp': No such file or directory	nSkinz	

and warnings like:
nonstandard extension used: nameless struct/union (compiling source file src\Hooks\PostDataUpdate.cpp)	

When trying to compile in visual studio

**Comment by namazso** [comment]
you failed at the very first step of the build guide

**Comment by CalvinBens** [comment]
> you failed at the very first step of the build guide
First of all, thanks for the snappy response. 

Second, I may have genuinely been dropped as a child since I cannot find this mentioned "build guide". Unless your talking about the read me, in which I'd still be confused.

**Comment by namazso** [comment]
yes it's the readme, and the very first step is to do a recursive clone

**Comment by CalvinBens** [comment]
> yes it's the readme, and the very first step is to do a recursive clone

Strange, I did exactly that, or at least I think I did. I pasted the command given in the git console and got the nSkinz file. Did I miss something?

**Comment by namazso** [comment]
well, you probably didnt or messed up somewhere along the way because it works on my machine
![image](https://user-images.githubusercontent.com/8676443/126088472-f026a2af-945b-45cc-85e5-2535d25abee1.png)

**Comment by CalvinBens** [comment]
> well, you probably didnt or messed up somewhere along the way because it works on my machine

Strange, doesn't look much different from mine. 
![Capture](https://user-images.githubusercontent.com/81130904/126088677-78aa8ab0-6bbd-4e18-891a-64d6859f2525.PNG)

**Comment by CalvinBens** [comment]
I downloaded it as a zip file and added the jason and imgui manually along with reinstalling visual studio 2019. Works now.
