### ISSUE TITLE
Cant compile (strstr)

### ISSUE THREAD

**Issue by rappingninjaYT** [namazso/nSkinz#237]
![devenv_HY0T2He8k2](https://user-images.githubusercontent.com/55623622/127173443-83216dc5-0c50-48dc-9de8-16230147c681.png)
![devenv_QNbJnaj5VT](https://user-images.githubusercontent.com/55623622/127173447-8955358f-6b89-431c-a81a-57d3b777825b.png)

i cant understand, the instructions are really vague.

**Comment by splitz189** [comment]
i have the same problem any fix yet?
