### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by R0m41n3** [namazso/nSkinz#24]
Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	LNK2001	unresolved external symbol "long __cdecl ImGui_ImplWin32_WndProcHandler(struct HWND__ *,unsigned int,unsigned int,long)" (?ImGui_ImplWin32_WndProcHandler@@YAJPAUHWND__@@IIJ@Z)	nSkinz	C:\Users\deadp\Documents\GitHub\nSkinz\Renderer.obj	1	Build

**Comment by namazso** [comment]
Fixed. the PR from terry only updated the function naming, but not the actual submodule
