### ISSUE TITLE
Compiling with errors

### ISSUE THREAD

**Issue by Slddev** [namazso/nSkinz#240]
Error:
Starting build...
"D:\User Profiles\SappyFiles\mingw\mingw64\bin\cpp.exe" -g D:\nSkinz\src\nSkinz.cpp -o D:\nSkinz\src\nSkinz.exe
In file included from D:\nSkinz\src\SDK/CBaseEntity.hpp:4,
                 from D:\nSkinz\src\SDK.hpp:8,
                 from D:\nSkinz\src\nSkinz.hpp:26,
                 from D:\nSkinz\src\nSkinz.cpp:25:
D:/nSkinz/src/Utilities/netvar_manager.hpp:106:49: warning: backslash-newline at end of file
  106 | #define NETPROP(funcname, class_name, var_name) \
      |                                                  

Build finished with warning(s).

**Comment by namazso** [comment]
that's not an error, that's a warning
