### ISSUE TITLE
I cant rename any of the skins

### ISSUE THREAD

**Issue by noxipoop** [namazso/nSkinz#25]
Whenever I try to click on the text boxes or try to move the sliders it cycles through the the boxes and sliders and im not able to do anything until i click out of the menu... It also crashes my game when i click load on my config :(

![giphy](https://user-images.githubusercontent.com/31017961/32091004-1dade34c-baa7-11e7-8c17-abd5b612b92c.gif)

**Comment by namazso** [comment]
Weird issue. Did you try building a fresh clone? Does the issue still persist?

**Comment by noxipoop** [comment]
I've fixed it. It was something wrong with my computer where it just spams the prtcn button
