### ISSUE TITLE
VAC Error

### ISSUE THREAD

**Issue by noxipoop** [namazso/nSkinz#27]
http://prntscr.com/h3qtup
I just got vac error-ed using this. Is it cause of the junk code?
UPDATE: I have removed most of the junk code and it still vac errors me :/

**Comment by wasnlosdu** [comment]
This is by design, the code injects itself into CS:GO. It essentially does what a cheat would do, so don't use it on Secure Servers. It's just for fun.

**Comment by namazso** [comment]
Whatever "junk code" you did you did it wrong and its still detected, which gets you kicked. if you want an easy way of changing the resulting code significantly i can recommend tampering around with compile options, or using another compiler
