### ISSUE TITLE
changed the signature and gave this to friends, they crash

### ISSUE THREAD

**Issue by iBrooda** [namazso/nSkinz#29]
So I gave this to some friends and they are crashing while I am not..

**Comment by noxipoop** [comment]
how did you change the signature?

**Comment by iBrooda** [comment]
@noxipoop youtube is free.. or you can use a brain fucking moron


im genuinely confused about this problem tho 🤔

**Comment by noxipoop** [comment]
@iBrooda I dont know why youre being a little bitch all i asked was how you changed the signatures. If you looked around at the issues tab you would see that i tried adding junk code and it wouldnt work. I was told using difference compiling settings worked and I thought thats what you did. You gotta calm down buddy stop being a fucking bitchass.

**Comment by namazso** [comment]
Thats not too detailed..

Have you modified nSkinz in any way?
In case you did is the original crashing?
When does the crash occour?
How are you injecting?
Have you tried debugging?

**Comment by iBrooda** [comment]
@namazso 
1 : Nothing has been changed
2 : Crash occurs on injection
3 : Injecting via ManualMapping
4 : They refuse to download vs and since I am not able to re-create the problem on my PC I can't debug it.

Thanks :)

**Comment by namazso** [comment]
It's not like vs would be useful for debugging manual mapped things anyways. Try recreating it on your computer with the same injector.

**Comment by iBrooda** [comment]
@namazso They use the same injector I use.. I just downloaded it and changed nothing. Sent it to them and they still crash. I'm completely lost

**Comment by namazso** [comment]
do they crash with LoadLibrary too? Some manualmappers crash if they fail

**Comment by iBrooda** [comment]
@namazso I will check.

**Comment by iBrooda** [comment]
@namazso sorry for the 6 day delay :^)
but loadlibrary isn't crashing however manual mapping is

**Comment by namazso** [comment]
Then it is an issue in your manual mapper. The update checker and possibly other parts are using c++ exceptions which your mapper probably doesnt fix. Fox your mapper.

**Comment by iBrooda** [comment]
@namazso Couldn't I just remove the exceptions?

**Comment by namazso** [comment]
Of course that would work too

**Comment by iBrooda** [comment]
@namazso okay so I removed the exceptions in Configuration.cpp and UpdateCheck.cpp

however I there was something I forgot cause still crashing

**Comment by namazso** [comment]
Debug..

**Comment by iBrooda** [comment]
im not the one crashing 🤦‍♂️
