### ISSUE TITLE
VAC Auth Error

### ISSUE THREAD

**Issue by noxipoop** [namazso/nSkinz#33]
Hey I added a lot of junk code and changed up the build settings and the signature change is now 49% but it still gives me a vac auth error... how do i fix this? higher signature change?

**Comment by noxipoop** [comment]
If you can help me get a private build I can pay >.< DrawdE#3956

**Comment by TronexEngine** [comment]
I can help you with it if you want.

**Comment by noxipoop** [comment]
Hey are you able to help me on discord? DrawdE#3956

**Comment by namazso** [comment]
Preventing VAC detections is not in the scope of this project. Also, junk code is useless / inferior for multiple reasons which I wont explain here. Please refrain from posting similar issues to this issue tracker in the future.

Closed.
