### ISSUE TITLE
Disconnect by VAC

### ISSUE THREAD

**Issue by deardid** [namazso/nSkinz#39]
I added some junk code and compiled, but I ended up being disconnected by vac, my friends had the same problem, I searched for a solution and I didn't find.

**Comment by nimaxmodz** [comment]
probably your injector

**Comment by namazso** [comment]
Preventing VAC detections is not in the scope of this project. Also, junk code is useless / inferior for multiple reasons which I wont explain here. Please refrain from posting similar issues to this issue tracker in the future.

Closed.
