### ISSUE TITLE
Menu crashing

### ISSUE THREAD

**Issue by noxipoop** [namazso/nSkinz#40]
My game crashes when i try to open the menu... The only thing i did was add the new hydra gloves and VMP the dll

**Comment by namazso** [comment]
Please confirm the presence of the issue on an unmodified copy

**Comment by toxiicdev** [comment]
Crashing :)

**Comment by Riaxx** [comment]
It may happen because of the vmp ;D

**Comment by namazso** [comment]
closed - not confirmed on original nSkinz, and opener seems to be away
