### ISSUE TITLE
VAC Auth

### ISSUE THREAD

**Issue by ThomHvH** [namazso/nSkinz#41]
Added junk code, tried 2 different injectors. One of which I know has no issues and I still get the error.

**Comment by pashasmj** [comment]
+1

**Comment by a6d6061ed1** [comment]
try to inject with xenos manual map (kernel mode)

**Comment by namazso** [comment]
Preventing VAC detections is not in the scope of this project. Also, junk code is useless / inferior for multiple reasons which I wont explain here. Please refrain from posting similar issues to this issue tracker in the future.

Closed.

**Comment by pashasmj** [comment]
@a6d6061ed1  i was using xenos and banned for 3 times ,how to inject with xenos(i compile xenos with junkcode already)  and inject it with manual map
