### ISSUE TITLE
Mouse and keyboard input

### ISSUE THREAD

**Issue by lukipinguin** [namazso/nSkinz#43]
When menu open the game still receive mouse click and keyboard input.
Is this the case for you or just me ?

I have clone the repo and build it with no modification to the source (deps also got clone).
sry for bad english :/

**Comment by vasyadeagle** [comment]
Your problem lies within ImGui's WndProc handler.
Find "ImGui_ImplWin32_WndProcHandler" function and make it return true everywhere, with exception of the start and the end of said function.
