### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by toxiicdev** [namazso/nSkinz#46]
Just gave another try on this, crashes on W10 16299 (version 1709)

**Comment by wi1h** [comment]
going to need more information than that. did you try debugging? what’s the error?

**Comment by toxiicdev** [comment]
Dont know to be honest, but probably is something up with this current w10 (creator update - trash update)

**Comment by wi1h** [comment]
i have had zero problems on the creators update

**Comment by toxiicdev** [comment]
Which injector are you using?

**Comment by wi1h** [comment]
my own basic LoadLibrary injector

**Comment by vasyadeagle** [comment]
Why dontcha debug it, son? Windows 10 build shouldn't matter.
