### ISSUE TITLE
( !!! ) VACNET DETECT ( !!! )

### ISSUE THREAD

**Issue by lm-ao** [namazso/nSkinz#50]
beware... this has vacnet dEtecTION

i lost 3 accounts due to ows......................... when i just use knife & glove changer........

**Comment by wi1h** [comment]
yeah that’s just not true, you got banned from something else. it’s
literally impossible

**Comment by namazso** [comment]
VACnet obviously cannot detect skinchangers, however the new VAC module might be able to (and probably does) detect the engine hook. I'll consider rewriting it to avoid that

**Comment by namazso** [comment]
Fixed in 3e49191
