### ISSUE TITLE
how can i fix this ?

### ISSUE THREAD

**Issue by uselessz** [namazso/nSkinz#52]
![indice](https://user-images.githubusercontent.com/39864090/40880207-e632a140-6682-11e8-98c0-5aa91ea7b3d9.png)

HELP ME PLSSS

**Comment by uselessz** [comment]
![indice2](https://user-images.githubusercontent.com/39864090/40881535-521e892a-669f-11e8-99fd-c7ac3a44b044.png)

THE ENGLISH VERSION
(IM BRAZILIAN)

**Comment by namazso** [comment]
by following the readme
