### ISSUE TITLE
Crashes CS upon injecting

### ISSUE THREAD

**Issue by SeiGaXxd** [namazso/nSkinz#53]
Title explains everything, it's a manual mapping injector and I just can't get it to work

This is the only internal giving any problem with that injector

**Comment by PerolGamerPRO** [comment]
Yeah, i have a manual mapping injector and it crashes too, but if i use for example GameOwner it works fine.

**Comment by SeiGaXxd** [comment]
I just tried GameOwner and yeah, it works. Probably just problems with manual mapping injectors.

**Comment by namazso** [comment]
Fix your injector or remove features your injector doesn't support.
