### ISSUE TITLE
VACNet

### ISSUE THREAD

**Issue by noxipoop** [namazso/nSkinz#54]
If you have been using nskinz, do not use it anymore as it has been detected by vacnet for some reason... the account that ive been only using nskinz on just got banned by ow... (i averaged like 10 kills a game) i would use caution

**Comment by namazso** [comment]
Did you happen to use any version before 3e49191f56df89f771db534d9467eda246e7dd4d on the account?
Those are indeed detected by the hook check

**Comment by noxipoop** [comment]
does the new source fix the hookcheck stuff

**Comment by namazso** [comment]
Yes.
Please only submit issues present in mainline version next time, thanks.
