### ISSUE TITLE
Cant compile. LINK Errors

### ISSUE THREAD

**Issue by MemorableDeath** [namazso/nSkinz#56]
I use this Single Include  -> https://github.com/nlohmann/json/tree/develop/single_include/nlohmann

When I try to compile the source I get LINK errors https://hastebin.com/eguquhatev.scala

**Comment by namazso** [comment]
Your hastebin is unavailable.
Also, if you change / update the libraries and cannot deal with what you've caused thats not my problem.

**Comment by MemorableDeath** [comment]
i wasnt able to compile it gives out link errors about imgui .

**Comment by Jeimy041** [comment]
I fixed this by using the Imgui version 1.52

**Comment by MemorableDeath** [comment]
hmm okay
z
