### ISSUE TITLE
Keep getting errors

### ISSUE THREAD

**Issue by ajaxxxxxxx** [namazso/nSkinz#63]
I cloned, I'm using VS 2017 on Release x86, yet I get this bullshit.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'float.h': No such file or directory (compiling source file deps\imgui\imgui.cpp)	nSkinz	c:\users\jeremy\nskinz\deps\imgui\imgui.h	14	
Error	C1083	Cannot open include file: 'float.h': No such file or directory (compiling source file deps\imgui\examples\directx9_example\imgui_impl_dx9.cpp)	nSkinz	c:\users\jeremy\nskinz\deps\imgui\imgui.h	14	
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory (compiling source file src\config.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\cstddef	7	
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory (compiling source file src\Hooks\FrameStageNotify.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\cstddef	7	
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory (compiling source file src\Hooks\FireEventClientSide.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\cstddef	7	
Error	C1083	Cannot open include file: 'float.h': No such file or directory (compiling source file deps\imgui\imgui_draw.cpp)	nSkinz	c:\users\jeremy\nskinz\deps\imgui\imgui.h	14	
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory (compiling source file src\Hooks\Sequence.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\cstddef	7	
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory (compiling source file src\nSkinz.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\cstddef	7	
Error	C1083	Cannot open include file: 'corecrt.h': No such file or directory (compiling source file src\sticker_changer.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\crtdefs.h	10	
Error	C1083	Cannot open include file: 'ctype.h': No such file or directory (compiling source file src\dllmain.cpp)	nSkinz	c:\program files (x86)\windows kits\8.1\include\um\winnt.h	31	
Error	C1083	Cannot open include file: 'corecrt.h': No such file or directory (compiling source file src\kit_parser.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\crtdefs.h	10	
Error	C1083	Cannot open include file: 'corecrt.h': No such file or directory (compiling source file src\update_check.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\crtdefs.h	10	
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory (compiling source file src\Utilities\platform.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\cstddef	7	
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory (compiling source file src\render.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\cstddef	7	
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory (compiling source file src\Utilities\netvar_manager.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\cstddef	7	
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory (compiling source file src\gui.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\cstddef	7	
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory (compiling source file src\item_definitions.cpp)	nSkinz	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\cstddef	7	
`

**Comment by Jeimy041** [comment]
Try to reinstall visual studio + reinstall the microsoft SDK

**Comment by namazso** [comment]
Something is broken with your vs installation, these are standard headers.
