### ISSUE TITLE
Undetected?

### ISSUE THREAD

**Issue by sigmataf** [namazso/nSkinz#65]
So this is undetected by v a c n e t? :thonk:

**Comment by Jeimy041** [comment]
The hooking method is modified in order to make it undetected, so yes it´s undetected for now

**Comment by sigmataf** [comment]
Thank you. Do you use it? ^^

**Comment by Jeimy041** [comment]
Yes I do, haven't been banned since I started using it

**Comment by Jeimy041** [comment]
If it gives you VAc error you will have to VMProtect it in order to make it anti VAc error

**Comment by sigmataf** [comment]
kk thank you dude i really appreciate it
