### ISSUE TITLE
Crashes on Panorama

### ISSUE THREAD

**Issue by toxiicdev** [namazso/nSkinz#67]
Tested the skin changer with new Panorama UI.

The client.dll (now client_panorama.dll) patterns are of course changed

However g_sequence_hook makes in-game crash.

Probably some indexes changed

**Comment by namazso** [comment]
Normal update stuff fixed in ebfd2896d763b72ca986b5304b859b7b3570a1c2 and 6dc5812d5c1a1c01419b17ad950c4a716535f59a
Panorama compatibility will happen when the update that forces it comes out

**Comment by toxiicdev** [comment]
after the fixes, panorama is running fine!

thanks for the work.

**Comment by namazso** [comment]
there are various lightning bugs and similar going on in panorama, so i wouldn't put much effort into investigating issues that might not even be related to the cheat. So i don't plan on investigating it until the update comes out for real.

**Comment by toxiicdev** [comment]
@namazso yea, but in my case happens only after injecting nSkinz
