### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by artrenxd** [namazso/nSkinz#71]
The skinchanger works pretty fine in the CS:GO main menu; but when i load a map and open the menu, my cursor gets stuck in the middle. Any fixes? A lot of people say it works fine. I wonder if i cause this issue. But I haven't changed anything in the source. Even reinstalling didn't help.

**Comment by Jeimy041** [comment]
Happens the same to me, after opening the menu press ESC to open the pause meno and the mouse will work then

**Comment by namazso** [comment]
Fixed in 2db69b008855bd9c5033a74b5651df74304293a3
