### ISSUE TITLE
Can Some one give me steps how to inject

### ISSUE THREAD

**Issue by Nolyth** [namazso/nSkinz#73]
I dont know how to inject i would like to get steps

**Comment by M1XT3NZ** [comment]
give me 3 minutes and i have a video up for you...

**Comment by M1XT3NZ** [comment]
https://www.youtube.com/watch?v=nj_Om7Wxyf0&feature=youtu.be

**Comment by anarh1st47** [comment]
nice video, but if there are a lot of question about compiling/injecting, may be maintailers will make a github release with binaries? why not

**Comment by M1XT3NZ** [comment]
Because it will be almost insta detected. and you need to add junkcode or you get insta banned too. 
so no reason for making a git release with binaries
