### ISSUE TITLE
Dll pls

### ISSUE THREAD

**Issue by Tobyyx3** [namazso/nSkinz#75]
I can't compile to a dll can someone send me the dll?
discord: Toby#6954

**Comment by chat1337** [comment]
i can send u but its crahsing, do u want it?

**Comment by Jeimy041** [comment]
Did you add the required libraries to the deps folder?

**Comment by Jeimy041** [comment]
I can send you the dll that is working without panorama, the panorama working one I have not compiled it yet but I can give you the one that works wiothout panorama

**Comment by chat1337** [comment]
Ey, @Jeimy041 can u send me the source code? (Without panorama)
Discord chat#4376

**Comment by M1XT3NZ** [comment]
the newest source is with or without panorama it doesnt matter if you play with it or if you not play with it...

**Comment by chat1337** [comment]
@M1XT3NZ yeah i know, but its crahsing for me when i inject it

**Comment by M1XT3NZ** [comment]
i will test it and watch if it crashes for me

**Comment by Solor** [comment]
hey guys, could you upload the lastest compiled dll file?

**Comment by M1XT3NZ** [comment]
So game doesnt crash for me in the old ui and not in the new.
with the source that is here on github
so i guess its kinda a you problem. 
@Solor and no that wouldnt be a good idea because you will probably be instant banned.

**Comment by namazso** [comment]
No binaries will be provided due to the nature of VAC. Any binaries released would almost instantly get hashed / sigged.
