### ISSUE TITLE
is this safe?

### ISSUE THREAD

**Issue by adilthequickdropper** [namazso/nSkinz#83]
sorry, since of all the vac waves and shit i only got 1 account and i plan to play legit but i want to have skins.. anyway is this safe or no

**Comment by anarh1st47** [comment]
looks like safe: it doesnt hook any blacklisted objects

**Comment by wardinh0** [comment]
I got banned using it with ~99% difference signature on sigbench (tested at least 200 times), injected with Rando (with about 1.5K lines of emit bytes).  More friends reported bans using similar methods of obfuscation. I can't confirm tho, some people say it's safe, some people say it's not. We'll need to wait for the next update to see if namazso says something.

**Comment by namazso** [comment]
last time i checked (second update after vac update banwave) they weren't checking any of these objects, and they don't really have a reason to either, so this shouldn't be fundamentally detected.
