### ISSUE TITLE
Will the new knives be available?

### ISSUE THREAD

**Issue by Jeimy041** [namazso/nSkinz#84]
Title says all, oh and btw Panorama is now compulsory to use

**Comment by Loliragi** [comment]
You can still use scaleform, just put -scaleform in your launch settings

**Comment by sonicrules11** [comment]
1. Just wait
2. Add them yourself
3. Use scaleform by putting `-scaleform` in your launch options

**Comment by Jeimy041** [comment]
Ok thx

**Comment by xbread** [comment]
Why not add the new knives in yourself there is a thread on UC

**Comment by namazso** [comment]
Now.

**Comment by Jeimy041** [comment]
Hahaha XD Thanks man!!!!
