### ISSUE TITLE
Got lot of errors (update with new skins)

### ISSUE THREAD

**Issue by jamowatz** [namazso/nSkinz#86]
Hey im tryin' to compile new nSkinz update but i got these errors: https://scr.hu/NoergP
pls help

PROBLEM FIXED ANYONE HAVE THIS PROBLEM 
HERES HOW IT SHOULD BE: https://scr.hu/kNkMrn

**Comment by jamowatz** [comment]
"błąd składniowy" means Syntax Error
and "brakuje" means missing
"przed" means before
and (stary styl formalnej funkcji) means old style of formal function
first error in example: error C2059: syntax error: "{"
2nd: error C2143: syntax error: missing ";" before "{"

**Comment by M1XT3NZ** [comment]
Did you add junk? Probably the junk fucked up. Double click the Error and
look at where you landed

**Comment by jamowatz** [comment]
i added junk, and got this, then i recloned it and didnt add junk, got this shiet again
thats where it is: https://scr.hu/mdm1gz  
every of this error is in line 65-81

**Comment by M1XT3NZ** [comment]
I saw what is redowbload the new version is already fixed in there

**Comment by jamowatz** [comment]
what?

**Comment by jamowatz** [comment]
im trying to compile version from 16 hrs ago

**Comment by M1XT3NZ** [comment]
Put the , behind the }

**Comment by jamowatz** [comment]
putted it
i got this shit: https://scr.hu/MAep5Gi
it says that ";" is syntax error lol

**Comment by M1XT3NZ** [comment]
Can’t view the screen but you need , not ;

**Comment by jamowatz** [comment]
seems to working but i fucked up some deps files xD
lemme reclone it again and ill say if workin ty

**Comment by jamowatz** [comment]
nah working, got more errors xD
https://scr.hu/kNkO1w

**Comment by jamowatz** [comment]
clear clone, added only ,

**Comment by jamowatz** [comment]
https://scr.hu/l8mYNr
now got it like that
what should i do

**Comment by M1XT3NZ** [comment]
The shadow daggers don’t have it

**Comment by jamowatz** [comment]
https://scr.hu/kNkMrn
https://scr.hu/kNkMrn
https://scr.hu/kNkMrn
FINALLY THANKS

**Comment by jamowatz** [comment]
man how to turn off every optimalization etc cuz my dll with shit tons of junk weights 300kb lol

**Comment by M1XT3NZ** [comment]
Google it. Can’t help ja because I’m not at home but right click on the
nSkinz and then properties

**Comment by jamowatz** [comment]
fixed it thanks, 1 option was on
