### ISSUE TITLE
imgui.h no such file or directory and so on

### ISSUE THREAD

**Issue by MuccaDiocan** [namazso/nSkinz#9]
Cant really compile it with windows 10 and visual studio community, I also tried manually adding the folders deps and imgui but when it compiles  i inject the dll and when i press INS nothing shows up.

**Comment by wi1h** [comment]
You have to go download imgui from [here](https://github.com/ocornut/imgui) and put it in deps/imgui/.

**Comment by MuccaDiocan** [comment]
Already tried that, used also git command to download nSkinz source, nothing to do:
1>------ Inizio compilazione: Progetto: nSkinz, Configurazione: Debug x64 ------
1>UpdateCheck.cpp
1>e:\download\nskinz-master\nskinz-master\nskinz\src\updatecheck.cpp(5): fatal error C1083: Non è possibile aprire il file inclusione: 'json.hpp': No such file or directory
1>Renderer.cpp
1>e:\download\nskinz-master\nskinz-master\nskinz\src\renderer.cpp(9): fatal error C1083: Non è possibile aprire il file inclusione: 'imgui.h': No such file or directory
1>Interface.cpp
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.hpp(21): warning C4244: '=': conversione da '__int64' a 'int'. Possibile perdita di dati.
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.hpp(55): warning C4244: '=': conversione da '__int64' a 'int'. Possibile perdita di dati.
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.hpp(60): warning C4244: '=': conversione da '__int64' a 'int'. Possibile perdita di dati.
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.hpp(67): warning C4244: '=': conversione da '__int64' a 'int'. Possibile perdita di dati.
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.hpp(74): warning C4244: '=': conversione da '__int64' a 'int'. Possibile perdita di dati.
1>e:\download\nskinz-master\nskinz-master\nskinz\src\interface.cpp(7): fatal error C1083: Non è possibile aprire il file inclusione: 'imgui.h': No such file or directory
1>Configuration.cpp
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.hpp(21): warning C4244: '=': conversione da '__int64' a 'int'. Possibile perdita di dati.
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.hpp(55): warning C4244: '=': conversione da '__int64' a 'int'. Possibile perdita di dati.
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.hpp(60): warning C4244: '=': conversione da '__int64' a 'int'. Possibile perdita di dati.
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.hpp(67): warning C4244: '=': conversione da '__int64' a 'int'. Possibile perdita di dati.
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.hpp(74): warning C4244: '=': conversione da '__int64' a 'int'. Possibile perdita di dati.
1>e:\download\nskinz-master\nskinz-master\nskinz\src\configuration.cpp(5): fatal error C1083: Non è possibile aprire il file inclusione: 'json.hpp': No such file or directory
1>imgui_impl_dx9.cpp
1>e:\download\nskinz-master\nskinz-master\nskinz\deps\imgui\imgui_impl_dx9.cpp(9): fatal error C1083: Non è possibile aprire il file inclusione: 'imgui.h': No such file or directory
1>Generazione del codice in corso...
1>Compilazione progetto "nSkinz.vcxproj" NON COMPLETATA.
========== Compilazione: 0 completate, 1 non riuscite, 0 aggiornate, 0 ignorate ==========

**Comment by namazso** [comment]
You are compiling in x64. Since CS:GO is 32bit you should compile in x86.

**Comment by namazso** [comment]
Also, I use LLVM to compile in release mode, so you'll probably have to change "Platform toolset" in project options, and remove the LLVM-specific parameters from additional compile parameters

**Comment by MuccaDiocan** [comment]
tried everything specified, now when i try to compile i get CL.exe exited with code 2, should I download LLVM and compile with the llvm toolset?

**Comment by MuccaDiocan** [comment]
Okay solved, thank you namazso :)
