### ISSUE TITLE
vac error

### ISSUE THREAD

**Issue by shixuxfaze** [namazso/nSkinz#92]
how to fix vac error? i cant play more than about 20mins, then i get vac errored

**Comment by Jeimy041** [comment]
VMP Protect the DLL and the Injector and the VAC Error will be gone

**Comment by shixuxfaze** [comment]
how to do it? whats vmp?

**Comment by shixuxfaze** [comment]
ok. ive got it, but my pc says: "you cant run this application on this pc" how can i fix it?

**Comment by M1XT3NZ** [comment]
vmp is vmprotect. you need to protect the dll and you injector with it.
