### ISSUE TITLE
nSkinz have a bunch of VAC Modules that can lead into Ban

### ISSUE THREAD

**Issue by troniac** [namazso/nSkinz#97]
Monitoring the VAC System for 24/7 and I get nearly any Modules now. Last time one VAC Module was very simple it counts VMTs and if it have different count as expected it loads another Module which check Signatures for VMTs if it catches unknown Sigs it streams another Module which I am currently analysing which I am not 100% sure what it does a friend on UC is currently looking into this cascaded Modules. There are different Detection Methods streamed packed into different Modules and they combine them to get a statistical aproach to Ban a player for 60% or 70% suspicious Modules. That is why some get banned using nSkinz and some are not.

**Comment by wardinh0** [comment]
This is very helpful, thank you. Do you have any threads on UC about this? I'd like to llok forward to it.

**Comment by namazso** [comment]
The VMT hook detection shit has been happening for months, none of the objects I use were checked last time I checked the modules. Also, whatever you mean by counting VMTs does not affect us, all objects I hook are dynamically allocated. Only the checks in random functions that `xor` table addresses and `or` a global variable have any effect on us. Feel free to post in this issue again in case you see that happening with any of our objects.
